dir: test/mocks
pkgname: mocks
template: testify
packages:
  github.com/lukso-network/tools-lukso-cli/api:
    config:
      filename: mock_api.go
      all: true
  github.com/lukso-network/tools-lukso-cli/api/logger:
    config:
      filename: mock_logger.go
      all: true
  github.com/lukso-network/tools-lukso-cli/common/file:
    config:
      filename: mock_file.go
      all: true
  github.com/lukso-network/tools-lukso-cli/common/installer:
    config:
      filename: mock_installer.go
      all: true
  github.com/lukso-network/tools-lukso-cli/common/progress:
    config:
      filename: mock_progress.go
      all: true
  github.com/lukso-network/tools-lukso-cli/config:
    config:
      filename: mock_config.go
      all: true
