dir: test/mocks
pkgname: mocks
template: testify
packages:
  github.com/lukso-network/tools-lukso-cli/api:
    config:
      all: true
  github.com/lukso-network/tools-lukso-cli/api/logger:
    config:
      all: true
  github.com/lukso-network/tools-lukso-cli/common/file:
    config:
      all: true
  github.com/lukso-network/tools-lukso-cli/common/installer:
    config:
      all: true
  github.com/lukso-network/tools-lukso-cli/common/progress:
    config:
      all: true
  github.com/lukso-network/tools-lukso-cli/config:
    config:
      all: true
