// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgress creates a new instance of MockProgress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgress(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgress {
	mock := &MockProgress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgress is an autogenerated mock type for the Progress type
type MockProgress struct {
	mock.Mock
}

type MockProgress_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgress) EXPECT() *MockProgress_Expecter {
	return &MockProgress_Expecter{mock: &_m.Mock}
}

// Hide provides a mock function for the type MockProgress
func (_mock *MockProgress) Hide() {
	_mock.Called()
	return
}

// MockProgress_Hide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hide'
type MockProgress_Hide_Call struct {
	*mock.Call
}

// Hide is a helper method to define mock.On call
func (_e *MockProgress_Expecter) Hide() *MockProgress_Hide_Call {
	return &MockProgress_Hide_Call{Call: _e.mock.On("Hide")}
}

func (_c *MockProgress_Hide_Call) Run(run func()) *MockProgress_Hide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProgress_Hide_Call) Return() *MockProgress_Hide_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgress_Hide_Call) RunAndReturn(run func()) *MockProgress_Hide_Call {
	_c.Run(run)
	return _c
}

// Move provides a mock function for the type MockProgress
func (_mock *MockProgress) Move(count float64) {
	_mock.Called(count)
	return
}

// MockProgress_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type MockProgress_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - count
func (_e *MockProgress_Expecter) Move(count interface{}) *MockProgress_Move_Call {
	return &MockProgress_Move_Call{Call: _e.mock.On("Move", count)}
}

func (_c *MockProgress_Move_Call) Run(run func(count float64)) *MockProgress_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *MockProgress_Move_Call) Return() *MockProgress_Move_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgress_Move_Call) RunAndReturn(run func(count float64)) *MockProgress_Move_Call {
	_c.Run(run)
	return _c
}

// Render provides a mock function for the type MockProgress
func (_mock *MockProgress) Render() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProgress_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockProgress_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
func (_e *MockProgress_Expecter) Render() *MockProgress_Render_Call {
	return &MockProgress_Render_Call{Call: _e.mock.On("Render")}
}

func (_c *MockProgress_Render_Call) Run(run func()) *MockProgress_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProgress_Render_Call) Return(s string) *MockProgress_Render_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProgress_Render_Call) RunAndReturn(run func() string) *MockProgress_Render_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockProgress
func (_mock *MockProgress) Set(goal float64) {
	_mock.Called(goal)
	return
}

// MockProgress_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockProgress_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - goal
func (_e *MockProgress_Expecter) Set(goal interface{}) *MockProgress_Set_Call {
	return &MockProgress_Set_Call{Call: _e.mock.On("Set", goal)}
}

func (_c *MockProgress_Set_Call) Run(run func(goal float64)) *MockProgress_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *MockProgress_Set_Call) Return() *MockProgress_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgress_Set_Call) RunAndReturn(run func(goal float64)) *MockProgress_Set_Call {
	_c.Run(run)
	return _c
}

// Show provides a mock function for the type MockProgress
func (_mock *MockProgress) Show() {
	_mock.Called()
	return
}

// MockProgress_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockProgress_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
func (_e *MockProgress_Expecter) Show() *MockProgress_Show_Call {
	return &MockProgress_Show_Call{Call: _e.mock.On("Show")}
}

func (_c *MockProgress_Show_Call) Run(run func()) *MockProgress_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProgress_Show_Call) Return() *MockProgress_Show_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProgress_Show_Call) RunAndReturn(run func()) *MockProgress_Show_Call {
	_c.Run(run)
	return _c
}

// Visible provides a mock function for the type MockProgress
func (_mock *MockProgress) Visible() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Visible")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProgress_Visible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Visible'
type MockProgress_Visible_Call struct {
	*mock.Call
}

// Visible is a helper method to define mock.On call
func (_e *MockProgress_Expecter) Visible() *MockProgress_Visible_Call {
	return &MockProgress_Visible_Call{Call: _e.mock.On("Visible")}
}

func (_c *MockProgress_Visible_Call) Run(run func()) *MockProgress_Visible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProgress_Visible_Call) Return(b bool) *MockProgress_Visible_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProgress_Visible_Call) RunAndReturn(run func() bool) *MockProgress_Visible_Call {
	_c.Call.Return(run)
	return _c
}
