// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/lukso-network/tools-lukso-cli/api/types"
	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Init provides a mock function with given fields: _a0
func (_m *MockHandler) Init(_a0 types.InitRequest) types.InitResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 types.InitResponse
	if rf, ok := ret.Get(0).(func(types.InitRequest) types.InitResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.InitResponse)
	}

	return r0
}

// MockHandler_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockHandler_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - _a0 types.InitRequest
func (_e *MockHandler_Expecter) Init(_a0 interface{}) *MockHandler_Init_Call {
	return &MockHandler_Init_Call{Call: _e.mock.On("Init", _a0)}
}

func (_c *MockHandler_Init_Call) Run(run func(_a0 types.InitRequest)) *MockHandler_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.InitRequest))
	})
	return _c
}

func (_c *MockHandler_Init_Call) Return(_a0 types.InitResponse) *MockHandler_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Init_Call) RunAndReturn(run func(types.InitRequest) types.InitResponse) *MockHandler_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function with given fields: _a0
func (_m *MockHandler) Install(_a0 types.InstallRequest) types.InstallResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 types.InstallResponse
	if rf, ok := ret.Get(0).(func(types.InstallRequest) types.InstallResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.InstallResponse)
	}

	return r0
}

// MockHandler_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockHandler_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - _a0 types.InstallRequest
func (_e *MockHandler_Expecter) Install(_a0 interface{}) *MockHandler_Install_Call {
	return &MockHandler_Install_Call{Call: _e.mock.On("Install", _a0)}
}

func (_c *MockHandler_Install_Call) Run(run func(_a0 types.InstallRequest)) *MockHandler_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.InstallRequest))
	})
	return _c
}

func (_c *MockHandler_Install_Call) Return(_a0 types.InstallResponse) *MockHandler_Install_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Install_Call) RunAndReturn(run func(types.InstallRequest) types.InstallResponse) *MockHandler_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function with given fields: _a0
func (_m *MockHandler) Logs(_a0 types.LogsRequest) types.LogsResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 types.LogsResponse
	if rf, ok := ret.Get(0).(func(types.LogsRequest) types.LogsResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.LogsResponse)
	}

	return r0
}

// MockHandler_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type MockHandler_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - _a0 types.LogsRequest
func (_e *MockHandler_Expecter) Logs(_a0 interface{}) *MockHandler_Logs_Call {
	return &MockHandler_Logs_Call{Call: _e.mock.On("Logs", _a0)}
}

func (_c *MockHandler_Logs_Call) Run(run func(_a0 types.LogsRequest)) *MockHandler_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.LogsRequest))
	})
	return _c
}

func (_c *MockHandler_Logs_Call) Return(_a0 types.LogsResponse) *MockHandler_Logs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Logs_Call) RunAndReturn(run func(types.LogsRequest) types.LogsResponse) *MockHandler_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function with given fields: _a0
func (_m *MockHandler) Reset(_a0 types.ResetRequest) types.ResetResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 types.ResetResponse
	if rf, ok := ret.Get(0).(func(types.ResetRequest) types.ResetResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.ResetResponse)
	}

	return r0
}

// MockHandler_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockHandler_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - _a0 types.ResetRequest
func (_e *MockHandler_Expecter) Reset(_a0 interface{}) *MockHandler_Reset_Call {
	return &MockHandler_Reset_Call{Call: _e.mock.On("Reset", _a0)}
}

func (_c *MockHandler_Reset_Call) Run(run func(_a0 types.ResetRequest)) *MockHandler_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ResetRequest))
	})
	return _c
}

func (_c *MockHandler_Reset_Call) Return(_a0 types.ResetResponse) *MockHandler_Reset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Reset_Call) RunAndReturn(run func(types.ResetRequest) types.ResetResponse) *MockHandler_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *MockHandler) Start(_a0 types.StartRequest) types.StartResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 types.StartResponse
	if rf, ok := ret.Get(0).(func(types.StartRequest) types.StartResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.StartResponse)
	}

	return r0
}

// MockHandler_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHandler_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 types.StartRequest
func (_e *MockHandler_Expecter) Start(_a0 interface{}) *MockHandler_Start_Call {
	return &MockHandler_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *MockHandler_Start_Call) Run(run func(_a0 types.StartRequest)) *MockHandler_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.StartRequest))
	})
	return _c
}

func (_c *MockHandler_Start_Call) Return(_a0 types.StartResponse) *MockHandler_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Start_Call) RunAndReturn(run func(types.StartRequest) types.StartResponse) *MockHandler_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: _a0
func (_m *MockHandler) Status(_a0 types.StatusRequest) types.StatusResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 types.StatusResponse
	if rf, ok := ret.Get(0).(func(types.StatusRequest) types.StatusResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.StatusResponse)
	}

	return r0
}

// MockHandler_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockHandler_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - _a0 types.StatusRequest
func (_e *MockHandler_Expecter) Status(_a0 interface{}) *MockHandler_Status_Call {
	return &MockHandler_Status_Call{Call: _e.mock.On("Status", _a0)}
}

func (_c *MockHandler_Status_Call) Run(run func(_a0 types.StatusRequest)) *MockHandler_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.StatusRequest))
	})
	return _c
}

func (_c *MockHandler_Status_Call) Return(_a0 types.StatusResponse) *MockHandler_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Status_Call) RunAndReturn(run func(types.StatusRequest) types.StatusResponse) *MockHandler_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: _a0
func (_m *MockHandler) Stop(_a0 types.StopRequest) types.StopResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 types.StopResponse
	if rf, ok := ret.Get(0).(func(types.StopRequest) types.StopResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.StopResponse)
	}

	return r0
}

// MockHandler_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockHandler_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - _a0 types.StopRequest
func (_e *MockHandler_Expecter) Stop(_a0 interface{}) *MockHandler_Stop_Call {
	return &MockHandler_Stop_Call{Call: _e.mock.On("Stop", _a0)}
}

func (_c *MockHandler_Stop_Call) Run(run func(_a0 types.StopRequest)) *MockHandler_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.StopRequest))
	})
	return _c
}

func (_c *MockHandler_Stop_Call) Return(_a0 types.StopResponse) *MockHandler_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Stop_Call) RunAndReturn(run func(types.StopRequest) types.StopResponse) *MockHandler_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *MockHandler) Update(_a0 types.UpdateRequest) types.UpdateResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 types.UpdateResponse
	if rf, ok := ret.Get(0).(func(types.UpdateRequest) types.UpdateResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.UpdateResponse)
	}

	return r0
}

// MockHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 types.UpdateRequest
func (_e *MockHandler_Expecter) Update(_a0 interface{}) *MockHandler_Update_Call {
	return &MockHandler_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *MockHandler_Update_Call) Run(run func(_a0 types.UpdateRequest)) *MockHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.UpdateRequest))
	})
	return _c
}

func (_c *MockHandler_Update_Call) Return(_a0 types.UpdateResponse) *MockHandler_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Update_Call) RunAndReturn(run func(types.UpdateRequest) types.UpdateResponse) *MockHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatorExit provides a mock function with given fields: _a0
func (_m *MockHandler) ValidatorExit(_a0 types.ValidatorExitRequest) types.ValidatorExitResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ValidatorExit")
	}

	var r0 types.ValidatorExitResponse
	if rf, ok := ret.Get(0).(func(types.ValidatorExitRequest) types.ValidatorExitResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.ValidatorExitResponse)
	}

	return r0
}

// MockHandler_ValidatorExit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorExit'
type MockHandler_ValidatorExit_Call struct {
	*mock.Call
}

// ValidatorExit is a helper method to define mock.On call
//   - _a0 types.ValidatorExitRequest
func (_e *MockHandler_Expecter) ValidatorExit(_a0 interface{}) *MockHandler_ValidatorExit_Call {
	return &MockHandler_ValidatorExit_Call{Call: _e.mock.On("ValidatorExit", _a0)}
}

func (_c *MockHandler_ValidatorExit_Call) Run(run func(_a0 types.ValidatorExitRequest)) *MockHandler_ValidatorExit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ValidatorExitRequest))
	})
	return _c
}

func (_c *MockHandler_ValidatorExit_Call) Return(_a0 types.ValidatorExitResponse) *MockHandler_ValidatorExit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_ValidatorExit_Call) RunAndReturn(run func(types.ValidatorExitRequest) types.ValidatorExitResponse) *MockHandler_ValidatorExit_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatorImport provides a mock function with given fields: _a0
func (_m *MockHandler) ValidatorImport(_a0 types.ValidatorImportRequest) types.ValidatorImportResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ValidatorImport")
	}

	var r0 types.ValidatorImportResponse
	if rf, ok := ret.Get(0).(func(types.ValidatorImportRequest) types.ValidatorImportResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.ValidatorImportResponse)
	}

	return r0
}

// MockHandler_ValidatorImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorImport'
type MockHandler_ValidatorImport_Call struct {
	*mock.Call
}

// ValidatorImport is a helper method to define mock.On call
//   - _a0 types.ValidatorImportRequest
func (_e *MockHandler_Expecter) ValidatorImport(_a0 interface{}) *MockHandler_ValidatorImport_Call {
	return &MockHandler_ValidatorImport_Call{Call: _e.mock.On("ValidatorImport", _a0)}
}

func (_c *MockHandler_ValidatorImport_Call) Run(run func(_a0 types.ValidatorImportRequest)) *MockHandler_ValidatorImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ValidatorImportRequest))
	})
	return _c
}

func (_c *MockHandler_ValidatorImport_Call) Return(_a0 types.ValidatorImportResponse) *MockHandler_ValidatorImport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_ValidatorImport_Call) RunAndReturn(run func(types.ValidatorImportRequest) types.ValidatorImportResponse) *MockHandler_ValidatorImport_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatorList provides a mock function with given fields: _a0
func (_m *MockHandler) ValidatorList(_a0 types.ValidatorListRequest) types.ValidatorListResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ValidatorList")
	}

	var r0 types.ValidatorListResponse
	if rf, ok := ret.Get(0).(func(types.ValidatorListRequest) types.ValidatorListResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.ValidatorListResponse)
	}

	return r0
}

// MockHandler_ValidatorList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorList'
type MockHandler_ValidatorList_Call struct {
	*mock.Call
}

// ValidatorList is a helper method to define mock.On call
//   - _a0 types.ValidatorListRequest
func (_e *MockHandler_Expecter) ValidatorList(_a0 interface{}) *MockHandler_ValidatorList_Call {
	return &MockHandler_ValidatorList_Call{Call: _e.mock.On("ValidatorList", _a0)}
}

func (_c *MockHandler_ValidatorList_Call) Run(run func(_a0 types.ValidatorListRequest)) *MockHandler_ValidatorList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ValidatorListRequest))
	})
	return _c
}

func (_c *MockHandler_ValidatorList_Call) Return(_a0 types.ValidatorListResponse) *MockHandler_ValidatorList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_ValidatorList_Call) RunAndReturn(run func(types.ValidatorListRequest) types.ValidatorListResponse) *MockHandler_ValidatorList_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with given fields: _a0
func (_m *MockHandler) Version(_a0 types.VersionRequest) types.VersionResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 types.VersionResponse
	if rf, ok := ret.Get(0).(func(types.VersionRequest) types.VersionResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.VersionResponse)
	}

	return r0
}

// MockHandler_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockHandler_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - _a0 types.VersionRequest
func (_e *MockHandler_Expecter) Version(_a0 interface{}) *MockHandler_Version_Call {
	return &MockHandler_Version_Call{Call: _e.mock.On("Version", _a0)}
}

func (_c *MockHandler_Version_Call) Run(run func(_a0 types.VersionRequest)) *MockHandler_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.VersionRequest))
	})
	return _c
}

func (_c *MockHandler_Version_Call) Return(_a0 types.VersionResponse) *MockHandler_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_Version_Call) RunAndReturn(run func(types.VersionRequest) types.VersionResponse) *MockHandler_Version_Call {
	_c.Call.Return(run)
	return _c
}

// VersionClients provides a mock function with given fields: _a0
func (_m *MockHandler) VersionClients(_a0 types.VersionClientsRequest) types.VersionClientsResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VersionClients")
	}

	var r0 types.VersionClientsResponse
	if rf, ok := ret.Get(0).(func(types.VersionClientsRequest) types.VersionClientsResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.VersionClientsResponse)
	}

	return r0
}

// MockHandler_VersionClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionClients'
type MockHandler_VersionClients_Call struct {
	*mock.Call
}

// VersionClients is a helper method to define mock.On call
//   - _a0 types.VersionClientsRequest
func (_e *MockHandler_Expecter) VersionClients(_a0 interface{}) *MockHandler_VersionClients_Call {
	return &MockHandler_VersionClients_Call{Call: _e.mock.On("VersionClients", _a0)}
}

func (_c *MockHandler_VersionClients_Call) Run(run func(_a0 types.VersionClientsRequest)) *MockHandler_VersionClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.VersionClientsRequest))
	})
	return _c
}

func (_c *MockHandler_VersionClients_Call) Return(_a0 types.VersionClientsResponse) *MockHandler_VersionClients_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_VersionClients_Call) RunAndReturn(run func(types.VersionClientsRequest) types.VersionClientsResponse) *MockHandler_VersionClients_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
