// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockInstaller is an autogenerated mock type for the Installer type
type MockInstaller struct {
	mock.Mock
}

type MockInstaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstaller) EXPECT() *MockInstaller_Expecter {
	return &MockInstaller_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: url
func (_m *MockInstaller) Fetch(url string) ([]byte, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInstaller_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockInstaller_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - url string
func (_e *MockInstaller_Expecter) Fetch(url interface{}) *MockInstaller_Fetch_Call {
	return &MockInstaller_Fetch_Call{Call: _e.mock.On("Fetch", url)}
}

func (_c *MockInstaller_Fetch_Call) Run(run func(url string)) *MockInstaller_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockInstaller_Fetch_Call) Return(body []byte, err error) *MockInstaller_Fetch_Call {
	_c.Call.Return(body, err)
	return _c
}

func (_c *MockInstaller_Fetch_Call) RunAndReturn(run func(string) ([]byte, error)) *MockInstaller_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// InstallFile provides a mock function with given fields: url, dest
func (_m *MockInstaller) InstallFile(url string, dest string) error {
	ret := _m.Called(url, dest)

	if len(ret) == 0 {
		panic("no return value specified for InstallFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstaller_InstallFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallFile'
type MockInstaller_InstallFile_Call struct {
	*mock.Call
}

// InstallFile is a helper method to define mock.On call
//   - url string
//   - dest string
func (_e *MockInstaller_Expecter) InstallFile(url interface{}, dest interface{}) *MockInstaller_InstallFile_Call {
	return &MockInstaller_InstallFile_Call{Call: _e.mock.On("InstallFile", url, dest)}
}

func (_c *MockInstaller_InstallFile_Call) Run(run func(url string, dest string)) *MockInstaller_InstallFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockInstaller_InstallFile_Call) Return(err error) *MockInstaller_InstallFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstaller_InstallFile_Call) RunAndReturn(run func(string, string) error) *MockInstaller_InstallFile_Call {
	_c.Call.Return(run)
	return _c
}

// InstallTar provides a mock function with given fields: url, dest
func (_m *MockInstaller) InstallTar(url string, dest string) error {
	ret := _m.Called(url, dest)

	if len(ret) == 0 {
		panic("no return value specified for InstallTar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstaller_InstallTar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallTar'
type MockInstaller_InstallTar_Call struct {
	*mock.Call
}

// InstallTar is a helper method to define mock.On call
//   - url string
//   - dest string
func (_e *MockInstaller_Expecter) InstallTar(url interface{}, dest interface{}) *MockInstaller_InstallTar_Call {
	return &MockInstaller_InstallTar_Call{Call: _e.mock.On("InstallTar", url, dest)}
}

func (_c *MockInstaller_InstallTar_Call) Run(run func(url string, dest string)) *MockInstaller_InstallTar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockInstaller_InstallTar_Call) Return(err error) *MockInstaller_InstallTar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstaller_InstallTar_Call) RunAndReturn(run func(string, string) error) *MockInstaller_InstallTar_Call {
	_c.Call.Return(run)
	return _c
}

// InstallZip provides a mock function with given fields: url, dest
func (_m *MockInstaller) InstallZip(url string, dest string) error {
	ret := _m.Called(url, dest)

	if len(ret) == 0 {
		panic("no return value specified for InstallZip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstaller_InstallZip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallZip'
type MockInstaller_InstallZip_Call struct {
	*mock.Call
}

// InstallZip is a helper method to define mock.On call
//   - url string
//   - dest string
func (_e *MockInstaller_Expecter) InstallZip(url interface{}, dest interface{}) *MockInstaller_InstallZip_Call {
	return &MockInstaller_InstallZip_Call{Call: _e.mock.On("InstallZip", url, dest)}
}

func (_c *MockInstaller_InstallZip_Call) Run(run func(url string, dest string)) *MockInstaller_InstallZip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockInstaller_InstallZip_Call) Return(err error) *MockInstaller_InstallZip_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstaller_InstallZip_Call) RunAndReturn(run func(string, string) error) *MockInstaller_InstallZip_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstaller creates a new instance of MockInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstaller {
	mock := &MockInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
