name: Simulate Success for Release PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  simulate_success_job:
    runs-on: ubuntu-latest
    steps:
      - name: Post success status for release chore.
        if: startsWith(github.event.pull_request.title, 'chore: release')
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Lint Test / lint_test'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - name: Post success status for testing (old status)
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'lint_test'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
